### ISSUE TITLE
Problem in DNS enumeration 

### ISSUE THREAD

**Issue by theNareshofficial** [thewhiteh4t/FinalRecon#70]
I tired python finalrecon.py --full --url http://thenareshofficial.free.nf/

 python finalrecon.py --full --url http://thenareshofficial.free.nf/

 
[!] Starting DNS Enumeration...

A       : 31.22.4.234
MX      : 10 sv62.ifastnet11.org.
NS      : ns3.byet.org.
NS      : ns2.free.nf.
NS      : ns4.byet.org.
NS      : ns5.byet.org.
NS      : ns2.byet.org.
NS      : ns1.byet.org.
NS      : ns1.free.nf.
SOA     : ns2.free.nf. support.free.nf. 2006112402 28800 7200 604800 86400
TXT     : "v=spf1 a mx ip4:207.182.136.179 ip4:209.190.85.158 ip4:209.190.9.26 ip4:209.190.9.26 ip4:69.197.12.1 ?all"
TXT     : "google-site-verification=-q6hxpsrckvmkht5bxmxpnleb6d1hzu9ma2ovnjevzw"
Traceback (most recent call last):
  File "/home/hunter/lab/tool/FinalRecon/finalrecon.py", line 254, in <module>
    dnsrec(hostname, dserv, out_settings, data)
  File "/home/hunter/lab/tool/FinalRecon/modules/dns.py", line 61, in dnsrec
    dmarc_ans = asyncio.run(fetch_records(res, dmarc_target, 'TXT'))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/hunter/lab/tool/FinalRecon/modules/dns.py", line 31, in fetch_records
    answer = await res.resolve(domain, record)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hunter/.local/lib/python3.11/site-packages/dns/asyncresolver.py", line 102, in resolve
    (answer, done) = resolution.query_result(response, None)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hunter/.local/lib/python3.11/site-packages/dns/resolver.py", line 836, in query_result
    raise NoAnswer(response=answer.response)
dns.resolver.NoAnswer: The DNS response does not contain an answer to the question: _dmarc.free.nf. IN TXT

I attempted to use another domain, but encountered similar issues like  python finalrecon.py --full --url https://selfmade.ninja/

**Comment by thewhiteh4t** [comment]
@theNareshofficial thanks! it looks like the issue is with domains which don't have a dmarc record, I will push a fix soon

**Comment by theNareshofficial** [comment]
Thanks @thewhiteh4t  ❤️

**Comment by thewhiteh4t** [comment]
@theNareshofficial I have pushed a patch, update using `git pull` and test again

![image](https://github.com/user-attachments/assets/efdba1f9-d99c-4ba8-9b63-f6bfc19602ee)

**Comment by theNareshofficial** [comment]
@thewhiteh4t  No, I still get some issues. I attached the below photo for your FYR.
![finalrecon issue](https://github.com/user-attachments/assets/8884ab90-770c-438a-834f-9faead0a212e)


I tried ❯  python finalrecon.py --full --url https://selfmade.ninja/


 ______  __   __   __   ______   __
/\  ___\/\ \ /\ "-.\ \ /\  __ \ /\ \
\ \  __\\ \ \\ \ \-.  \\ \  __ \\ \ \____
 \ \_\   \ \_\\ \_\\"\_\\ \_\ \_\\ \_____\
  \/_/    \/_/ \/_/ \/_/ \/_/\/_/ \/_____/
 ______   ______   ______   ______   __   __
/\  == \ /\  ___\ /\  ___\ /\  __ \ /\ "-.\ \
\ \  __< \ \  __\ \ \ \____\ \ \/\ \\ \ \-.  \
 \ \_\ \_\\ \_____\\ \_____\\ \_____\\ \_\\"\_\
  \/_/ /_/ \/_____/ \/_____/ \/_____/ \/_/ \/_/

[>] Created By   : thewhiteh4t
 |---> Twitter   : https://twitter.com/thewhiteh4t
 |---> Community : https://twc1rcle.com/
[>] Version      : 1.1.7

[+] Target : https://selfmade.ninja

[+] IP Address : 95.111.195.229
Traceback (most recent call last):
  File "/home/hunter/lab/tool/FinalRecon/finalrecon.py", line 248, in <module>
    from modules.dns import dnsrec
  File "/home/hunter/lab/tool/FinalRecon/modules/dns.py", line 4, in <module>
    import dns.asyncresolver
  File "/home/hunter/.local/lib/python3.11/site-packages/dns/asyncresolver.py", line 24, in <module>
    import dns._ddr
  File "/home/hunter/.local/lib/python3.11/site-packages/dns/_ddr.py", line 12, in <module>
    import dns.nameserver
  File "/home/hunter/.local/lib/python3.11/site-packages/dns/nameserver.py", line 5, in <module>
    import dns.asyncquery
  File "/home/hunter/.local/lib/python3.11/site-packages/dns/asyncquery.py", line 32, in <module>
    import dns.quic
  File "/home/hunter/.local/lib/python3.11/site-packages/dns/quic/__init__.py", line 7, in <module>
    import aioquic.quic.configuration  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/aioquic/quic/configuration.py", line 6, in <module>
    from ..tls import (
  File "/usr/lib/python3/dist-packages/aioquic/tls.py", line 26, in <module>
    import service_identity
  File "/usr/lib/python3/dist-packages/service_identity/__init__.py", line 6, in <module>
    from . import cryptography, hazmat, pyopenssl
  File "/usr/lib/python3/dist-packages/service_identity/pyopenssl.py", line 32, in <module>
    from OpenSSL.crypto import X509
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 34, in <module>
    from OpenSSL.crypto import (
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 942, in <module>
    utils.deprecated(
TypeError: deprecated() got an unexpected keyword argument 'name'

**Comment by thewhiteh4t** [comment]
@theNareshofficial share output of `pip show dnspython`

**Comment by theNareshofficial** [comment]
@thewhiteh4t I located the problem. A package on **cryptography pyOpenSSL** is the problem. After that, I reinstalled cryptography pyOpenSSL, and it is now functioning properly.

Thank you🤝

**Comment by thewhiteh4t** [comment]
@theNareshofficial that's great!
